### ISSUE TITLE
m_math.h license? :D

### ISSUE THREAD

**Issue by r-lyeh** [ands/spherical_harmonics_playground#1]
Hey @ands,

I was thinking about adding m_math.h and parts of the SPH coeffs into my engine, which is unlicensed/public domain.

What's the license of those files? And the repo license as whole? Could they be PD/Unlicensed/CC0?

Thank you in advance :)
- r-lyeh.

PS: Keep up the good work! :)

**Comment by r-lyeh** [comment]
Ah, I think I could also reuse fps camera & texture cube loading as well! :)
I will properly credit where its due of course :D

Ty!

**Comment by ands** [comment]
Sure, go ahead and use those :) Will add a PD header/license file as soon as I'm back home. Keep in mind though that imgui, stb, yocto_obj, glfw and the cube maps are not mine and thus licensed separately!

**Comment by r-lyeh** [comment]
Woo-hoo Ty!!  :))

**Comment by ands** [comment]
Added headers to my own source files. Have fun! :)
