### ISSUE TITLE
Where does the `32.0f` come from?

### ISSUE THREAD

**Issue by Liby99** [ands/spherical_harmonics_playground#2]
Hello! This is a very straightforward project! I'm trying to reproduce the result myself but I have a question about the formula you use to calculate the coefficients.

https://github.com/ands/spherical_harmonics_playground/blob/9675001636bb5567c08f82a3c95fcfdc8e0efa2e/main.cpp#L212

More specifically, what is the `32.0f` in this line? And in past papers we usually see a `pi` in the formula but I don't see any in yours. Do you have any idea of what's going on there?

**Comment by ands** [comment]
Hey! That was just a bad hack I did back then due to limited understanding. :) Sorry about that.
It should be 4*PI / sampleWeightsSum instead of 32.0f / samples.
Thanks for noticing, I'll update the code asap!
